inherit_gem:
  rubocop-rails:
    - config/rails.yml

Layout/StringLiterals:
  Enabled: false

Layout/StringLiteralsInInterpolation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: normal
